1. Import the numpy package under the name np (★☆☆)

In [1]:
import numpy as np

2. Print the numpy version and the configuration (★☆☆)

In [73]:
import numpy as np

dir(np)

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__array_namespace_info__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_array_api_info',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'around',
 'array',
 'arr

In [74]:
print(np.__version__)

2.3.5


In [75]:
np.show_config

<function numpy.show_config(mode='stdout')>

## 📌 Learnings

- `np.__version__` se NumPy ka version dekhte hain.
- `np.show_config()` NumPy ki configuration dikhata hai.
- `dir(np)` use karke kisi package ke functions explore kar sakte hain.

## ❓ Mistakes

- Pehle `np.show_config` likha tha, `()` lagana bhool gaya.
- `__array_api_version__` ko NumPy version samajh liya tha.




3. Create a null vector of size 10 (★☆☆)

In [76]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## 📌 Learnings

1. `np.zeros` ek function hai.
2. Function ko execute karne ke liye `()` use hote hain.
3. `[]` indexing ke liye use hote hain.
4. Pehle function array banata hai, uske baad hi us array par `[]` laga sakte hain.

4. How to find the memory size of any array (★☆☆)
   

In [77]:
arr = np.array([1,5,6,4])
arr.nbytes

32

## 📌 Learnings

1. `dtype` batata hai ki array ke elements kis type ke hain.
2. `nbytes` batata hai ki poora array kitni memory use kar raha hai.
3. `nbytes` ka logic hai:

   Total Memory = Number of Elements × Bytes per Element

5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [78]:
help



Type help() for interactive help, or help(object) for help about object.

In [79]:
np.add?

Signature:       np.add(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'add'>
File:            c:\users\prince\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:      
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` a

## Learnings

- Documentation ka matlab function ka manual hota hai.
- `help(function)` se documentation dekh sakte hain.
- JupyterLab me `function?` likhkar bhi documentation dekh sakte hain.
- `function??` aur bhi detailed information dikhata hai.

6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [80]:
arr = np.zeros(10, dtype=np.int64)
print(arr)
print(arr.dtype)

[0 0 0 0 0 0 0 0 0 0]
int64


In [81]:
arr


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [82]:
arr[4]=1


In [83]:
arr

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

## Learnings

1. Python me indexing 0 se start hoti hai.
2. 5th element ka index 4 hota hai.
3. Array ki value ko update karne ke liye:

   arr[index] = value

4. np.zeros() default me float64 array banata hai.

7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [84]:
arr=np.arange(10,50,1)

In [85]:
arr


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

## Learnings

- `np.arange()` sequence banata hai.
- Syntax: `np.arange(start, stop, step)`
- `start` include hota hai.
- `stop` include nahi hota.
- `step` default `1` hota hai.

8. Reverse a vector (first element becomes last) (★☆☆)
   

In [86]:
arr = np.arange(10,20)
print(arr)
print(arr[ : : -1])

[10 11 12 13 14 15 16 17 18 19]
[19 18 17 16 15 14 13 12 11 10]


## Learnings

1. Reverse ka matlab array ko ulta karna hota hai.
2. Reverse karne ke baad:
   - First element → Last
   - Last element → First
3. NumPy me slicing ka use karke vector ko reverse kar sakte hain.
4. Slicing ka syntax hota hai:
   
   arr[start:stop:step]

5. Agar step = -1 ho to array reverse direction me traverse hota hai.
6. `arr[::-1]` poore array ko reverse kar deta hai.  


    ## Objective

- Array Slicing ko samajhna.
- Negative step (-1) ka use samajhna.
- Reverse traversal ka concept seekhna.


    ## Common Mistake

Maine pehle socha tha ki reverse ka matlab mirror banana hota hai.

Example:
[1,2,3] → [1,2,3,3,2,1] ❌

Lekin reverse ka matlab hota hai:

[1,2,3] → [3,2,1] ✅ 


    ## Revision Point

Reverse = arr[::-1]

9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [87]:
arr = np.arange(0,9)

In [88]:
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [89]:
dir(arr)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_namespace__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__buffer__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',


In [90]:
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [91]:
arr= np.arange(12)
print(arr.reshape(2,6))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


## Learnings

1. `reshape()` array ki shape badalta hai.
2. Data change nahi hota, sirf arrangement change hota hai.
3. `rows × columns` hamesha `total elements` ke barabar hona chahiye.
4. Agar multiplication match nahi karega to `ValueError` aayega.

10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [92]:
arr =np.array([1,2,0,0,4,0])



In [93]:
arr !=0

array([ True,  True, False, False,  True, False])

In [94]:
np.where(arr != 0)


(array([0, 1, 4]),)

## Learnings

1. `np.where()` condition ke basis par indices return karta hai.
2. Pehle condition likhte hain, jaise:
   - arr != 0
   - arr > 10
   - arr == 5
3. Jahan condition `True` hoti hai, unka index return hota hai.
4. Jahan condition `False` hoti hai, unhe ignore kar diya jata hai.

11. Create a 3x3 identity matrix

In [95]:
arr = np.eye(3,3)

In [96]:
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Learnings

1. Identity Matrix me main diagonal par 1 hote hain.
2. Baaki sab elements 0 hote hain.
3. Identity Matrix banane ke liye `np.eye()` use karte hain.
4. `np.eye(3)` aur `np.eye(3,3)` dono 3×3 identity matrix banate hain.

12. Create a 3x3x3 array with random values (★☆☆)

In [7]:
dir(np.random)

['BitGenerator',
 'Generator',
 'MT19937',
 'PCG64',
 'PCG64DXSM',
 'Philox',
 'RandomState',
 'SFC64',
 'SeedSequence',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_bounded_integers',
 '_common',
 '_generator',
 '_mt19937',
 '_pcg64',
 '_philox',
 '_pickle',
 '_sfc64',
 'beta',
 'binomial',
 'bit_generator',
 'bytes',
 'chisquare',
 'choice',
 'default_rng',
 'dirichlet',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_bit_generator',
 'get_state',
 'gumbel',
 'hypergeometric',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_bit_generator',
 'set_state',
 'shuf

In [8]:
np.random.random_sample?

Signature: np.random.random_sample(size=None)
Docstring:
random_sample(size=None)

Return random floats in the half-open interval [0.0, 1.0).

Results are from the "continuous uniform" distribution over the
stated interval.  To sample :math:`Unif[a, b), b > a` multiply
the output of `random_sample` by `(b-a)` and add `a`::

  (b - a) * random_sample() + a

.. note::
    New code should use the `~numpy.random.Generator.random`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
size : int or tuple of ints, optional
    Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
    ``m * n * k`` samples are drawn.  Default is None, in which case a
    single value is returned.

Returns
-------
out : float or ndarray of floats
    Array of random floats of shape `size` (unless ``size=None``, in which
    case a single float is returned).

See Also
--------
random.Generator.random: which should be used for ne

In [17]:
np.random.random_sample(size=(3,3,3))

array([[[0.92372853, 0.78853951, 0.11137874],
        [0.48636121, 0.01462554, 0.63370937],
        [0.27015474, 0.64430649, 0.61853427]],

       [[0.36428475, 0.98408857, 0.53695169],
        [0.1544915 , 0.02639084, 0.48148084],
        [0.06134454, 0.10116804, 0.82629382]],

       [[0.1391728 , 0.75350835, 0.16346625],
        [0.83799289, 0.34789699, 0.97821215],
        [0.01651955, 0.07515999, 0.51496646]]])

## Learnings

1. `np.random.random_sample()` random values generate karta hai.
2. Output ki shape `size` parameter decide karta hai.
3. Agar multiple dimensions chahiye, to `size` me tuple pass karte hain.
4. `size=(3,3,3)` ka matlab 3D array banana hai.

13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [18]:
arr = np.random.random_sample(size= (10,10))

In [19]:
arr


array([[0.39506948, 0.32666089, 0.48181627, 0.18840425, 0.70604676,
        0.35158033, 0.2330096 , 0.43710199, 0.73623071, 0.34384279],
       [0.50841831, 0.22226713, 0.40268772, 0.79096581, 0.10063525,
        0.22364803, 0.19983073, 0.40704931, 0.35585001, 0.96767194],
       [0.99111927, 0.21151949, 0.03443392, 0.65721401, 0.40708668,
        0.82602488, 0.50994144, 0.61199126, 0.63459419, 0.03899853],
       [0.97968317, 0.97809833, 0.74517989, 0.47611881, 0.97736618,
        0.47264514, 0.75457171, 0.21914313, 0.15460035, 0.68446947],
       [0.78131033, 0.84858247, 0.05616335, 0.19318322, 0.13691321,
        0.25529527, 0.541368  , 0.28177271, 0.50265646, 0.47842712],
       [0.73278573, 0.47112425, 0.50689529, 0.78907361, 0.41148524,
        0.88375025, 0.59897923, 0.73327182, 0.26873305, 0.61535699],
       [0.69501945, 0.64762466, 0.54649207, 0.2292284 , 0.79288774,
        0.14699901, 0.52163224, 0.64255318, 0.63456385, 0.77871546],
       [0.10933389, 0.11630922, 0.4214925

In [23]:
print("minimum" ,arr.min())
print("maximum" ,arr.max())

minimum 0.03443391838848564
maximum 0.9916318505569469


## Learnings

1. `np.random.random_sample((m,n))` random values ka array banata hai.
2. `arr.min()` array ki smallest value return karta hai.
3. `arr.max()` array ki largest value return karta hai.
4. `random_sample()` default me 0 se 1 ke beech values generate karta hai.
- `arr.min()` aur `arr.max()` ek single value (NumPy scalar) return karte hain, array nahi.
- NumPy scalar ki shape `()` hoti hai.

In [24]:
np.min(arr)
np.max(arr)

np.float64(0.9916318505569469)

In [25]:
arr.shape

(10, 10)

14. Create a random vector of size 30 and find the mean value (★☆☆)

In [29]:
np.random.randint?

Signature: np.random.randint(low, high=None, size=None, dtype=<class 'int'>)
Docstring:
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the `~numpy.random.Generator.integers`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-lik

In [32]:
arr = np.random.randint(low = 1 ,high =100,size= (30)) 

In [33]:
arr

array([22,  3,  8, 70, 64, 60, 53, 51, 28, 95, 65, 84, 23, 38, 77, 18, 10,
       67, 78,  6, 26, 88, 13, 75, 89, 77, 14,  5, 29, 27], dtype=int32)

In [35]:
arr.mean()

np.float64(45.43333333333333)

### Learnings

1. `mean()` array ke sabhi elements ka average return karta hai.
2. `arr.mean()` aur `np.mean(arr)` dono same result dete hain.
3. Mean integer aur float arrays dono par kaam karta hai.

15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [81]:
import numpy as np
arr = np.ones((5,5 ), dtype= int)

In [82]:
arr


array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [83]:
arr[1:4,1:4]=0


In [84]:
arr


array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

### Learnings

1. 2D array me slicing ka syntax hota hai:
   arr[rows, columns]

2. Border ko chhodkar andar wale elements select karne ke liye slicing use karte hain.

3. Python slicing me last index include nahi hota.

4. 10×10 array me inside area:
   arr[1:9, 1:9]

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [92]:
arr = np.random.randint(low =1, high=100,size=(3,4))

In [93]:
arr


array([[49, 74, 44, 18],
       [35,  7, 45, 31],
       [11,  1, 96,  5]], dtype=int32)

In [94]:
# arr[0:1]=0
#  arr[-1]=0
# arr[: ,0:1]=0
# arr [: , -1]=0


In [95]:
# arr

In [96]:
arr2 = np.zeros((5,6))

In [97]:
arr2

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [100]:
arr2[1:4,1:5]= arr

In [101]:
arr2

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0., 49., 74., 44., 18.,  0.],
       [ 0., 35.,  7., 45., 31.,  0.],
       [ 0., 11.,  1., 96.,  5.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [102]:
arr2[1:4,1:5].shape

(3, 4)

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [103]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


## Learnings

1. `np.nan` ka matlab "Not a Number" hota hai.
2. `nan` ke saath arithmetic karne par result aksar `nan` hi hota hai.
3. `np.nan == np.nan` hamesha `False` hota hai.
4. `np.inf` ko `nan` ke saath compare karne par meaningful comparison nahi hota.
5. Floating point numbers (`0.1`, `0.2`, `0.3`) binary representation ki wajah se exact nahi hote.

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [122]:
arr= np.random.randint(low=1,high=20 ,size=(5,5))

In [123]:
arr

array([[15,  2, 17, 19, 10],
       [ 7, 15, 16, 10,  3],
       [16,  9, 11, 10,  4],
       [19, 19,  7, 19, 14],
       [13,  2,  4,  1, 17]], dtype=int32)

In [124]:
arr[0:1,0:1]=1
arr[1:2,1:2]=2
arr[2:3,2:3]=3
arr[3:4,3:4]=4
arr[4:5,4:5]=5

In [125]:
arr

array([[ 1,  2, 17, 19, 10],
       [ 7,  2, 16, 10,  3],
       [16,  9,  3, 10,  4],
       [19, 19,  7,  4, 14],
       [13,  2,  4,  1,  5]], dtype=int32)

In [127]:
arr = np.zeros((5,5))

arr[1:2,0:1]=1
arr[2:3,1:2]=2
arr[3:4,2:3]=3
arr[4:5,3:4]=4

In [128]:
arr

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

### Learnings

1. Main diagonal ke indexes hote hain:
   (0,0), (1,1), (2,2)...

2. Diagonal ke just below indexes hote hain:
   (1,0), (2,1), (3,2), (4,3)

3. Single element access ke liye:
   arr[row, column]

4. Slicing (1:2) ki zarurat tab hoti hai jab multiple elements select karne hon.

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)



In [161]:
arr= np.zeros((8,8),dtype=int)

In [162]:
arr

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [165]:
arr[0::2,1::2]=1
arr[1::2,0::2]=1

In [166]:
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

### Learnings

1. `arr[rows]` sirf rows select karta hai.
2. `arr[rows, columns]` rows aur columns ke intersection ko select karta hai.
3. `0::2` = even indexes.
4. `1::2` = odd indexes.
5. 2D slicing me row aur column ko combine karke specific pattern banaya ja sakta hai.

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)  



In [167]:
# 6= block
# 7 = row
# 8 =column

# row*column = 7*8 = 56 
# elemnet = 100 / 56 ,quotient = 1 its means block = 1
# 100-56= 44
# remaining value is 44 divide by row quentity like 8

# 44/8 =  ,  quotient = 5 and remaining = 4

# that mean row 5 and colum 4


### Learnings

1. Shape (6,7,8) means:
   - 6 blocks
   - 7 rows
   - 8 columns

2. One block contains:
   7 × 8 = 56 elements

3. To convert a flat index into a 3D index:
   - Block = index // (rows × columns)
   - Offset = index % (rows × columns)
   - Row = offset // columns
   - Column = offset % columns

4. NumPy uses 0-based indexing, so always check whether a question means "100th element" (counting from 1) or "index 100".

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)



In [18]:
import numpy as np
arr= np.tile([[0,1],[1,0]],(4,4))
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [19]:
arr =  np.array([1,2,3,4])
np.tile(arr,3)

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4])

### Learning:

1. np.tile() is used to repeat an array or pattern multiple times.
   Syntax: np.tile(array, (row_repeat, column_repeat))

2. In np.tile(), repetition values represent the number of blocks repeated in rows and columns, not the final array size.

22. Normalize a 5x5 random matrix (★☆☆)



In [25]:
arr=np.random.randint(low=1,high=100,size=((5,5)))
print("min",arr.min())
print("max",arr.max())
arr

min 1
max 98


array([[45, 70, 66, 84, 17],
       [ 2, 97, 41, 65, 13],
       [68, 97, 71,  2,  8],
       [24, 37, 92, 24, 82],
       [ 1, 47, 58, 98, 82]], dtype=int32)

In [34]:
arr=(arr-arr.min())/(arr.max()-arr.min())
arr

array([[0.54639175, 0.28865979, 0.32989691, 0.1443299 , 0.83505155],
       [0.98969072, 0.01030928, 0.58762887, 0.34020619, 0.87628866],
       [0.30927835, 0.01030928, 0.27835052, 0.98969072, 0.92783505],
       [0.7628866 , 0.62886598, 0.06185567, 0.7628866 , 0.16494845],
       [1.        , 0.5257732 , 0.41237113, 0.        , 0.16494845]])

### Learning:

1. Normalization scales data between 0 and 1.

2. Min-Max normalization:
   X_new = (X - X_min) / (X_max - X_min)

3. Parentheses are important because they decide the order of calculation.

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)



In [37]:
color_dtype= np.dtype([('R', np.uint8),('G', np.uint8),('B', np.uint8),('A', np.uint8)])

In [38]:
color_dtype

dtype([('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])

### Learning:

1. np.dtype() is used to create a custom/structured data type in NumPy.

2. Custom dtype allows us to define the structure of data before storing it.
   Example: A color can be defined with four fields:
   Red, Green, Blue, Alpha (RGBA).

3. np.uint8 represents unsigned byte values, which stores values from 0 to 255.

4. Custom dtype is useful when we have many similar records and want to store them in a fixed format.

### Concept:

dtype works like a template.
First we define how our data should look,
then all data follows the same structure.

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)



In [49]:
a= np.random.randint(1,20,size=(5,3))
b = np.random.randint(1,25, size=(3,2))
c = np.dot(a,b)


In [50]:
a


array([[ 4,  2, 12],
       [ 7, 15,  9],
       [19,  7, 10],
       [19,  2,  7],
       [17,  9, 15]], dtype=int32)

In [51]:
b

array([[21,  8],
       [20, 14],
       [21,  4]], dtype=int32)

In [52]:
c

array([[376, 108],
       [636, 302],
       [749, 290],
       [586, 208],
       [852, 322]], dtype=int32)

In [53]:
c.shape

(5, 2)

### Learning:

1. np.dot() performs matrix multiplication in NumPy.

2. Matrix multiplication is possible when the first matrix columns are equal to the second matrix rows.

3. The shape of output is:
   (first matrix rows, second matrix columns)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)



In [55]:
arr = np.random.randint(1,20 ,size = (13))
arr

array([14,  4,  4, 17, 15, 13, 10, 10,  5,  5,  5, 19,  6], dtype=int32)

In [56]:
arr[(arr>=3 )& (arr<=8)] *=-1
arr

array([14, -4, -4, 17, 15, 13, 10, 10, -5, -5, -5, 19, -6], dtype=int32)

### Learning:
*= -1 ="Unki value ka sign ulta kar do."
1. Boolean indexing is used to select array elements based on a condition.

2. Multiplying values by -1 changes their sign (positive to negative and negative to positive).

3. In-place operations modify the original array without creating a new array.

In [57]:

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))


9
10


### Learning:

1. Python sum() and NumPy np.sum() are different functions.

2. from numpy import * can overwrite existing Python functions.

3. Always prefer importing NumPy as np and use np.function_name().

In [63]:
Z =np.array([1,2,3])
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
# Z<Z>Z

array([1., 2., 3.])

### Learning:

1. NumPy operators work element-wise on arrays.

2. Arithmetic operators return calculated values.

3. Comparison operators return boolean arrays.

4. Chained comparisons like Z<Z>Z are not supported because NumPy arrays contain multiple boolean values.

5. Use &, | instead of and/or for combining NumPy conditions.

In [66]:
np.array(0)/np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

C:\Users\prince\AppData\Local\Temp\ipykernel_8660\3220095231.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0)/np.array(0)
C:\Users\prince\AppData\Local\Temp\ipykernel_8660\3220095231.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
C:\Users\prince\AppData\Local\Temp\ipykernel_8660\3220095231.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

### Learning:

1. NaN represents missing or undefined floating-point values.

2. NaN cannot be stored in integer dtype.

3. Division by zero in NumPy often gives warnings and special values like NaN instead of stopping execution.

4. astype() is used for converting NumPy array datatype.

29. How to round away from zero a float array ? (★☆☆)



In [67]:
arr = np.array([1.2,2.7,-1.2,-2.7])
result = np.where(arr>0,np.ceil(arr),np.floor(arr))
print(result)

[ 2.  3. -2. -3.]


### Learning:

1. Rounding away from zero means increasing the magnitude of a number.

2. Positive numbers use ceil(), negative numbers use floor().

3. np.where() helps apply different operations based on a condition.

30. How to find common values between two arrays? (★☆☆)



In [79]:
arr1= np.random.randint(1,20,size=(15))
arr2 = np.random.randint(1,20,size=(15))


In [80]:
arr1

array([ 8,  1,  5,  8,  9,  4,  8, 18, 12, 12,  3, 14, 19, 14, 17],
      dtype=int32)

In [81]:
arr2

array([14, 16, 13,  3,  5,  1,  2, 13, 14,  2, 16, 10, 12, 18, 11],
      dtype=int32)

In [82]:
np.intersect1d(arr1,arr2)

array([ 1,  3,  5, 12, 14, 18], dtype=int32)

### Learning:

1. np.intersect1d() finds common elements between two arrays.

2. It returns sorted unique common values.

3. Intersection means the values present in both arrays.

31How to ignore all numpy warnings (not recommended)? (★☆☆)




In [83]:
# np.seterr(all='ignore')

# arr = np.array([1,0])

# print(arr/0)

[inf nan]



### Learning:

1. np.seterr(all='ignore') is used to ignore NumPy warnings.

2. NumPy warnings help identify problems like divide by zero and invalid operations.

3. Ignoring all warnings is not recommended because it can hide errors.



In [84]:
np.sqrt(-1) == np.emath.sqrt(-1)

np.False_

### Learning:

1. np.sqrt() works with real numbers and returns nan for negative inputs.

2. np.emath.sqrt() supports complex numbers and can calculate square roots of negative values.

3. sqrt(-1) is represented as 1j in Python.

33. How to get the dates of yesterday, today and tomorrow? (★☆☆)



In [87]:
today= np.datetime64('today')
yesterday = today-np.timedelta64(1,'D')
tomorrow = today + np.timedelta64(1,'D')
print("Today" ,today)
print("Yesterday",yesterday)
print("Tomorrow",tomorrow)

Today 2026-07-08
Yesterday 2026-07-07
Tomorrow 2026-07-09


34. How to get all the dates corresponding to the month of July 2016? (★★☆)



In [90]:
date= np.arange(
    np.datetime64('2016-07'),
    np.datetime64('2016-08'),
    np.timedelta64(1,"D")
)
print(date)


['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


### Learning:

1. np.arange() can generate a sequence of dates.

2. np.datetime64() represents dates.

3. np.timedelta64() defines the step between dates.

4. Date range includes start date but excludes the stop date.

35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)



In [91]:
# normal tarika:

A = np.array([2,4,6], dtype=float)
B = np.array([1,3,5], dtype=float)

result = (A+B)*(-A/2)

print(result)

[ -3. -14. -33.]


In [95]:

A = np.array([2,4,6], dtype=float)
B = np.array([1,3,5], dtype=float)

np.add(A,B, out=A)
A*= -(A-B)/2
A


array([ -3., -14., -33.])

### Learning:

1. In-place operations modify the existing NumPy array instead of creating a new copy.

2. Operators like +=, -=, *=, /= update the original array directly.

3. NumPy functions provide the `out` parameter to store results in an existing array.

4. In-place operations help reduce memory usage when working with large arrays.

5. `-0.5` and `-1/2` are mathematically equivalent.

36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)




In [106]:
arr = np.array([1.23, 5.89, 10.45, 7.99],dtype=np.int64)
arr

array([ 1,  5, 10,  7])

In [99]:
arr.astype(int)

array([ 1,  5, 10,  7])

In [107]:
floor(arr)

array([ 1,  5, 10,  7])

In [108]:
np.trunc(arr)

array([ 1,  5, 10,  7])

37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)



In [115]:
arr= np.array([0,1,2,3,4])
np.tile(arr,(5,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [111]:
arr= np.zeros((5,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [118]:
arr[0::]=0,1,2,3,4
arr.astype(int)
arr

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [119]:
arr = np.arange(5)

arr = np.tile(arr,(5,1))
arr

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

### Learning:

1. np.tile() repeats an array according to the given shape.

2. np.tile(arr,(5,1)) means repeat the row 5 times.

3. np.tile(arr,(5,5)) repeats both rows and columns, creating extra columns.

4. NumPy broadcasting allows assigning a 1D array to every row of a 2D array.

5. Shape matching is important while assigning values in NumPy arrays.

38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)



In [124]:
def generator():
    for i in range(1,11):
        yield i
        
arr= np.array(list(generator()))

arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Learning:

1. Generator functions use `yield` to produce values one at a time.

2. Generators are memory efficient because they do not store all values at once.

3. A generator can be converted into a list and then into a NumPy array.

4. `yield` pauses the function and resumes from the same point when the next value is requested.

39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)



In [20]:
import numpy as np 
np.linspace(0,1,10)


array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [24]:
arr=np.linspace(0,1,12)
arr

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])

In [29]:
new_arr=arr[1:-1]
new_arr

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [30]:
arr


array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])

In [31]:
new_arr

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [32]:
arr = np.linspace(0,1,12)[1:-1]

In [33]:
arr

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

### Learning:

1. `np.linspace()` is used when we need a fixed number of evenly spaced values between two points.

2. By default, `np.linspace()` includes both start and end points.

3. When endpoints are not required, slicing can be used:
   - `arr[1:]` removes the first element.
   - `arr[:-1]` removes the last element.
   - `arr[1:-1]` removes both first and last elements.

4. NumPy slicing does not modify the original array automatically. It returns a sliced view/result.

5. To save the sliced result, assign it back:
   
   `arr = arr[1:-1]`

6. `np.arange()` uses step size, while `np.linspace()` uses the number of values required.

40. Create a random vector of size 10 and sort it (★★☆)



In [35]:
arr=np.random.randint(1,10,size=10)
np.sort(arr)

array([1, 1, 1, 3, 3, 5, 5, 7, 8, 9], dtype=int32)

### Learning:

1. `np.sort()` returns a sorted copy of an array.

2. `array.sort()` modifies the original array in-place.

3. Sorting arranges elements in ascending order by default.

41. How to sum a small array faster than np.sum? (★★☆)



In [36]:
arr= np.array([1,2,8,4])
sum(arr)

np.int64(15)

### Learning:

1. `np.sum()` is optimized for large NumPy arrays.

2. For very small arrays, Python built-in functions can sometimes be faster because NumPy function calls have overhead.

3. Performance depends on data size, not only on the function.

4. Always choose tools according to the problem size.

In [37]:
import numpy as np
import time

# small array
arr = np.random.randint(1, 100, size=10)

print("Array:", arr)

# Python built-in sum()
start = time.time()

result1 = sum(arr)

end = time.time()

print("Python sum result:", result1)
print("Python sum time:", end - start)


# NumPy np.sum()
start = time.time()

result2 = np.sum(arr)

end = time.time()

print("NumPy sum result:", result2)
print("NumPy sum time:", end - start)

Array: [65 16  5 30 44  2 53 28 85 99]
Python sum result: 427
Python sum time: 4.696846008300781e-05
NumPy sum result: 427
NumPy sum time: 6.961822509765625e-05


42. Consider two random arrays A and B, check if they are equal (★★☆)



In [43]:
arr1=np.random.randint(1,30,size=10)
arr2= np.random.randint(1,30,size=10)
arr1

array([18, 12,  5, 12, 11, 18, 13, 13, 15, 28], dtype=int32)

In [44]:
arr2

array([29, 10,  5,  9, 23,  6, 23, 17, 11, 26], dtype=int32)

In [46]:
np.array_equal(arr1,arr2)


False

### Learning:

1. `==` compares elements one by one.

2. Array equality requires checking all elements.

3. NumPy provides functions to compare complete arrays.

4. For floating point arrays, approximate comparison is often safer than exact comparison.

43. Make an array immutable (read-only) (★★☆)



In [47]:
arr= np.arange(1,20,3)
arr


array([ 1,  4,  7, 10, 13, 16, 19])

In [48]:
arr.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [51]:
arr.flags.writeable=False

In [52]:
arr

array([ 1,  4,  7, 10, 13, 16, 19])

In [53]:
arr[2]=126

ValueError: assignment destination is read-only

### NumPy Array Flags:

- `arr.flags` → array ki properties dikhata hai.
- `writeable=True` → array modify kar sakte hain.
- `writeable=False` → array read-only ban jata hai.

44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)



In [56]:
arr= np.random.randint(1,50,size=(10,2))

In [57]:
arr

array([[42, 23],
       [ 2, 48],
       [16, 38],
       [ 1, 26],
       [35, 24],
       [48, 48],
       [44, 32],
       [48,  4],
       [38,  8],
       [32, 49]], dtype=int32)

In [63]:
x= arr[:,0]
x

array([42,  2, 16,  1, 35, 48, 44, 48, 38, 32], dtype=int32)

In [64]:
y = arr[:,1]
y

array([23, 48, 38, 26, 24, 48, 32,  4,  8, 49], dtype=int32)

In [65]:
r = np.sqrt(x**2 + y**2)
r

array([47.88527958, 48.0416486 , 41.23105626, 26.01922366, 42.43819035,
       67.88225099, 54.40588203, 48.16637832, 38.83297568, 58.52349955])

In [66]:
theta = np.arctan2(y,x)
theta


array([0.50101339, 1.52915375, 1.17227388, 1.53235374, 0.60107375,
       0.78539816, 0.62879629, 0.08314123, 0.20749623, 0.99227211])

In [ ]:
polar = np.column_stac