1. Import the numpy package under the name np (★☆☆)

In [72]:
import numpy as np

2. Print the numpy version and the configuration (★☆☆)

In [73]:
import numpy as np

dir(np)

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__array_namespace_info__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_array_api_info',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'around',
 'array',
 'arr

In [74]:
print(np.__version__)

2.3.5


In [75]:
np.show_config

<function numpy.show_config(mode='stdout')>

## 📌 Learnings

- `np.__version__` se NumPy ka version dekhte hain.
- `np.show_config()` NumPy ki configuration dikhata hai.
- `dir(np)` use karke kisi package ke functions explore kar sakte hain.

## ❓ Mistakes

- Pehle `np.show_config` likha tha, `()` lagana bhool gaya.
- `__array_api_version__` ko NumPy version samajh liya tha.




3. Create a null vector of size 10 (★☆☆)

In [76]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## 📌 Learnings

1. `np.zeros` ek function hai.
2. Function ko execute karne ke liye `()` use hote hain.
3. `[]` indexing ke liye use hote hain.
4. Pehle function array banata hai, uske baad hi us array par `[]` laga sakte hain.

4. How to find the memory size of any array (★☆☆)
   

In [77]:
arr = np.array([1,5,6,4])
arr.nbytes

32

## 📌 Learnings

1. `dtype` batata hai ki array ke elements kis type ke hain.
2. `nbytes` batata hai ki poora array kitni memory use kar raha hai.
3. `nbytes` ka logic hai:

   Total Memory = Number of Elements × Bytes per Element

5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [78]:
help



Type help() for interactive help, or help(object) for help about object.

In [79]:
np.add?

Signature:       np.add(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'add'>
File:            c:\users\prince\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:      
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` a

## Learnings

- Documentation ka matlab function ka manual hota hai.
- `help(function)` se documentation dekh sakte hain.
- JupyterLab me `function?` likhkar bhi documentation dekh sakte hain.
- `function??` aur bhi detailed information dikhata hai.

6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [80]:
arr = np.zeros(10, dtype=np.int64)
print(arr)
print(arr.dtype)

[0 0 0 0 0 0 0 0 0 0]
int64


In [81]:
arr


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [82]:
arr[4]=1


In [83]:
arr

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

## Learnings

1. Python me indexing 0 se start hoti hai.
2. 5th element ka index 4 hota hai.
3. Array ki value ko update karne ke liye:

   arr[index] = value

4. np.zeros() default me float64 array banata hai.

7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [84]:
arr=np.arange(10,50,1)

In [85]:
arr


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

## Learnings

- `np.arange()` sequence banata hai.
- Syntax: `np.arange(start, stop, step)`
- `start` include hota hai.
- `stop` include nahi hota.
- `step` default `1` hota hai.

8. Reverse a vector (first element becomes last) (★☆☆)
   

In [86]:
arr = np.arange(10,20)
print(arr)
print(arr[ : : -1])

[10 11 12 13 14 15 16 17 18 19]
[19 18 17 16 15 14 13 12 11 10]


## Learnings

1. Reverse ka matlab array ko ulta karna hota hai.
2. Reverse karne ke baad:
   - First element → Last
   - Last element → First
3. NumPy me slicing ka use karke vector ko reverse kar sakte hain.
4. Slicing ka syntax hota hai:
   
   arr[start:stop:step]

5. Agar step = -1 ho to array reverse direction me traverse hota hai.
6. `arr[::-1]` poore array ko reverse kar deta hai.  


    ## Objective

- Array Slicing ko samajhna.
- Negative step (-1) ka use samajhna.
- Reverse traversal ka concept seekhna.


    ## Common Mistake

Maine pehle socha tha ki reverse ka matlab mirror banana hota hai.

Example:
[1,2,3] → [1,2,3,3,2,1] ❌

Lekin reverse ka matlab hota hai:

[1,2,3] → [3,2,1] ✅ 


    ## Revision Point

Reverse = arr[::-1]

9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [87]:
arr = np.arange(0,9)

In [88]:
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [89]:
dir(arr)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_namespace__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__buffer__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',


In [90]:
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [91]:
arr= np.arange(12)
print(arr.reshape(2,6))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


## Learnings

1. `reshape()` array ki shape badalta hai.
2. Data change nahi hota, sirf arrangement change hota hai.
3. `rows × columns` hamesha `total elements` ke barabar hona chahiye.
4. Agar multiplication match nahi karega to `ValueError` aayega.

10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [92]:
arr =np.array([1,2,0,0,4,0])



In [93]:
arr !=0

array([ True,  True, False, False,  True, False])

In [94]:
np.where(arr != 0)


(array([0, 1, 4]),)

## Learnings

1. `np.where()` condition ke basis par indices return karta hai.
2. Pehle condition likhte hain, jaise:
   - arr != 0
   - arr > 10
   - arr == 5
3. Jahan condition `True` hoti hai, unka index return hota hai.
4. Jahan condition `False` hoti hai, unhe ignore kar diya jata hai.

11. Create a 3x3 identity matrix

In [95]:
arr = np.eye(3,3)

In [96]:
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Learnings

1. Identity Matrix me main diagonal par 1 hote hain.
2. Baaki sab elements 0 hote hain.
3. Identity Matrix banane ke liye `np.eye()` use karte hain.
4. `np.eye(3)` aur `np.eye(3,3)` dono 3×3 identity matrix banate hain.

In [97]:
git status

SyntaxError: invalid syntax (3528599804.py, line 1)